### ISSUE TITLE
pip install doesn't work properly.

### ISSUE THREAD

**Issue by jznf** [shamrin/namesgenerator#8]
1) when pip installed, `ModuleNotFoundError: No module named 'namesgenerator'` when trying to import.

2) `pip freeze` or `list` shows `namesgenerator==0.1` even though https://pypi.python.org/pypi/namesgenerator shows only version  `0.2`

3) The above apply in fresh virtualenv and conda environments. When I try it in completely vanilla docker `python:latest` container pip installs version `0.2` but the problem remains the same. There is `/usr/local/lib/python3.6/site-packages/namesgenerator-0.2.dist-info` dir but the actual module is missing from site-packages, it's in /usr/local/bin/namesgenerator.py

I guess:
- There's some versions confusion
- It should go to `site-packages` otherwise it won't work.

**Comment by shamrin** [comment]
Seems to work now, but feel free to reopen. Thank you for reporting the issue!

```
$ mkdir test-pip
$ cd test-pip
$ virtualenv venv
$ venv/bin/pip install namesgenerator
Collecting namesgenerator
  Downloading namesgenerator-0.3.tar.gz
Building wheels for collected packages: namesgenerator
  Running setup.py bdist_wheel for namesgenerator ... done
  Stored in directory: /Users/asha/Library/Caches/pip/wheels/98/3a/af/4bce145846b8291a982777ba38da2ade33fc9519e80ba74932
Successfully built namesgenerator
Installing collected packages: namesgenerator
Successfully installed namesgenerator-0.3
$ venv/bin/python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import namesgenerator
>>> namesgenerator.get_random_name()
'xenodochial_minsky'
```
